### ISSUE TITLE
Null pointer expcetion at  CloudBlobContainer container = blobClient.getContainerReference("testcontainer");

### ISSUE THREAD

**Issue by maheshchunkhade** [Azure-Samples/storage-blob-android-photo-uploader#7]
am getting null pointer exception at  CloudBlobContainer container = blobClient.getContainerReference("testcontainer");

logs as below -

W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
2019-01-16 18:33:21.746 23922-24183/com.microsoft.photouploader W/System.err:     at com.microsoft.azure.storage.core.Utility.isHostDnsName(Utility.java:404)
2019-01-16 18:33:21.746 23922-24183/com.microsoft.photouploader W/System.err:     at com.microsoft.azure.storage.core.Utility.determinePathStyleFromUri(Utility.java:392)
2019-01-16 18:33:21.746 23922-24183/com.microsoft.photouploader W/System.err:     at com.microsoft.azure.storage.StorageUri.<init>(StorageUri.java:71)
2019-01-16 18:33:21.746 23922-24183/com.microsoft.photouploader W/System.err:     at com.microsoft.azure.storage.core.PathUtility.appendPathToUri(PathUtility.java:123)
2019-01-16 18:33:21.747 23922-24183/com.microsoft.photouploader W/System.err:     at com.microsoft.azure.storage.core.PathUtility.appendPathToUri(PathUtility.java:108)
2019-01-16 18:33:21.747 23922-24183/com.microsoft.photouploader W/System.err:     at com.microsoft.azure.storage.blob.CloudBlobContainer.<init>(CloudBlobContainer.java:205)
2019-01-16 18:33:21.747 23922-24183/com.microsoft.photouploader W/System.err:     at com.microsoft.azure.storage.blob.CloudBlobClient.getContainerReference(CloudBlobClient.java:133)
2019-01-16 18:33:21.747 23922-24183/com.microsoft.photouploader W/System.err:     at com.microsoft.photouploader.ImageManager.getContainer(ImageManager.java:57)
2019-01-16 18:33:21.748 23922-24183/com.microsoft.photouploader W/System.err:     at com.microsoft.photouploader.ImageManager.UploadImage(ImageManager.java:63)
2019-01-16 18:33:21.748 23922-24183/com.microsoft.photouploader W/System.err:     at com.microsoft.photouploader.MainActivity$4.run(MainActivity.java:101)
2019-01-16 18:33:21.748 23922-24183/com.microsoft.photouploader W/System.err:     at java.lang.Thread.run(Thread.java:764)

**Comment by sid374** [comment]
@maheshchunkhade How did you solve this issue? I'm running into this as well.

**Comment by BhargaviDeviYamanuri** [comment]
Is any one have solution for this even i'm also facing same problem. I have used latest azure version.
